# put all necessary details
[DEFAULT]
PAGE_TITLE = Langgraph: Build stateful Agentic AI Graph
LLM_OPTIONS = GROQ, OPENAI, ANTHROPIC
USECASE_OPTIONS = Basic Chatbot, Agentic Chatbot
GROQ_MODEL_OPTIONS = openai/gpt-oss-120b, llama-3.3-70b-versatile
